### PR TITLE
Added Main Functions for Unittest 

### PR DESCRIPTION
**Pull request by jesuisme**
I've added a main function to each of the test files to allow the unittest to work.

### CODE REVIEW

**Comment by mattspitz** [comment]
Sorry if I'm sticking my nose (no pun intended) into this too much, but have you considered using nosetests?

$ pip install nose
$ nosetests ./tests

It correctly finds all the TestCases for you and executes them a lot faster than running each file individually.  If you need to run a particular test case, you can always run
$ nosetests tests.test_integration

This would eliminate the need for this commit, but, as it is, it's harmless, so go for it!

**Comment by rustyrazorblade** [comment]
Agree w/ Matt.  Py.test will do the same thing.  Running unittests manually via the main() check is unnecessary.

**Comment by jesuisme** [comment]
Agreed.  I originally used manual testing while trying to figure out that the TypeError comes from using the wrong version of results.  How should I proceed - kill the fork?

**Comment by NateFerrero** [comment]
Looks like everyone is in agreement here, I'll close! I'm going to add a requirements.txt.

**Comment by rustyrazorblade** [comment]
Instead of using requirements.txt, the setup.py can specify a version number.

**Comment by NateFerrero** [comment]
It already does - so it looks like we're good here.

**Comment by rustyrazorblade** [comment]
I was literally editing my previous post to note that it's there, and I'm not sure the need for a separate requirements file.  You're a quick one.

**Comment by NateFerrero** [comment]
Too fast, one might say. Thanks for the input!

**Comment by jesuisme** [comment]
The fork is gone - thanks for the help and input everyone.

**Pull request closed without merging**
