### PR TITLE
replaced Crypto.Random with SystemRandom function

### PR DESCRIPTION
**Pull request by dm0dev**
this would remove the package depency to PyCrypto

### CODE REVIEW

**Comment by dmpeters** [comment]
Is there any traction on this pull request - is this something even being considered? I hope so :)

**Comment by NateFerrero** [comment]
Can you pull request this into my fork @dmglab 
https://github.com/NateFerrero/pyoauth2

I don't work at Shift anymore - I'll send them a big pull request once I've reviewed everything on my fork and ran tests etc.

**Comment by rustyrazorblade** [comment]
@dmpeters we're no longer maintaining this library, sorry.  Please see @NateFerrero's fork

**Comment by NateFerrero** [comment]
Thanks @rustyrazorblade

**Comment by dmpeters** [comment]
Sweet! Thx @rustyrazorblade

**Pull request closed without merging**
